# Generated by Django 6.0.3 on 2026-03-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
